name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: danieldrysdale/.github/.github/workflows/python-ci.yml@main
    with:
      python-version: '3.12'
      requirements-file: 'requirements-dev.txt'
      test-path: 'tests/'
      docker-build: true
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
